spring:
  profiles:
    include:
      - log
      - demo
      - druid
      - time
      - springdoc
      - mybatis-plus
      - redis
  banner:
    location: banner-larry3d.txt
#  config:
#    use-legacy-processing: true
