server:
  port: 8000
spring:
  application:
    name: service-demo
  profiles:
    active: @profile.active@
  config: # springboot_2.4 use different control logic in this.
    use-legacy-processing: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.driver
logging:
  file:
    name: service-demo