version: '3.0'
services:
#  需要自行配置nacos-mysql的配置
#  DONE: service 内存空间限制, cmd:
#  docker-compose --compatibility up -d
#  TODO [whywhathow] [2022/3/3] [must]  [nacos,sentinel] 源码配置方案
  fun-nacos:
    image: nacos/nacos-server
    container_name: fun-nacos
    environment:
      MODE: standalone
      JVM_XMS: 256m
      JVM_XMX: 256m
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500m


  fun-sentinel:
    build: sentinel-dashboard
    container_name: fun-sentinel
    ports:
      - "9527:9527"
    environment:
      SERVER_PORT: 9527
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 300m

  fun-redis:
#    需要密码登录 redis-cli -hYourHost -a YourPassword
    image: redis:6.2.6-alpine
#    build: redis
    container_name: fun-redis
    ports:
      - "16379:6379"
    user: root
    privileged: true
    command:
      - redis-server /etc/conf/redis.conf
    volumes:
      - ./redis/conf:/etc/conf
      - ./redis/data:/data
      - ./redis/logs:/logs #

#    image: fun-sentinel




