#spring:
#  redis:
#    host: ${REDIS_HOST:centos-product}
#    port: ${REDIS_PORT:6379}
#    password:
#    database:

# 引入sentinel 配置 , 避免sentinel处理uri级别的用户请求
spring:
  cloud:
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: ${SENTINEL_IP:centos-product}:${SENTINEL_PORT:9527}
      log:
        dir: /logs/sentinel/
      #spring.cloud.sentinel.datasource.ds2.nacos.server-addr=localhost:8848
      #spring.cloud.sentinel.datasource.ds2.nacos.data-id=sentinel
      #spring.cloud.sentinel.datasource.ds2.nacos.group-id=DEFAULT_GROUP
      #spring.cloud.sentinel.datasource.ds2.nacos.data-type=json
      #spring.cloud.sentinel.datasource.ds2.nacos.rule-type=degrade
      datasource:
        d1:
          nacos:
            server-addr: ${NACOS_IP:centos-product}:${NACOS_PORT:8848}
            data-id: sentinel-gateway
            group-id: gateway
            data-type: json
            rule-type: degrade