aj:
  captcha:
    type: blockpuzzle
    jigsaw: classpath:images/jigsaw # 滑块验证码图片所在位置
    pic-click: classpath:images/pic-click # 文字选择图片验证码所在位置
    cache-type: local # 缓存类型 TODO [whywhathow] [11/5/2022] [must] change to redis
    cache-number: 1000 # 缓存数量达到1000后清理
    timing-clear: 60
    water-mark: whywhathow.fun@gmail.com
    slip-offset: 5  # 滑块验证码误差范围(default 5)
    aes-status: true   # aes加密坐标开启或者禁用(true|false)
    interference-options: 2    # 滑动干扰项(0/1/2)
#    限流模块
    # 接口请求次数一分钟限制是否开启 true|false
    req-frequency-limit-enable: false
    # 验证失败5次，get接口锁定
    req-get-lock-limit: 5
    # 验证失败后，锁定时间间隔,s
    req-get-lock-seconds: 300
    # get接口一分钟内请求数限制
    req-get-minute-limit: 30
    # check接口一分钟内请求数限制
    req-check-minute-limit: 30



