spring:
  profiles:
    active: @profile.active@
  config: # springboot_2.4 use different control logic in this.
    use-legacy-processing: true
  datasource:
    username: root
    password: aa12321. #check
    url: jdbc:mysql://zero-product:3306/fun_system?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
#不需要 配置
#logging:
#  level:
#    com.fun.system.api.mapper: debug

