spring:
  task:
    execution:
      pool: # settings for core-thread timeout. true == core-thread can gc
        allow-core-thread-timeout: false
        core-size: 4 # core-threads num
        max-size: 8 # max-threads num
        queue-capacity: 1000
        keep-alive: 60
      thread-name-prefix: "Fun-Executor-"
    scheduling:
      pool:
        size: 2  #定时任务线程池大小,默认为1
